name: Docker Image CI

on:
  push:
    branches: 
      - master

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag docker.pkg.github.com/aiogram/bot/telegram:${GITHUB_SHA:0:8} --tag docker.pkg.github.com/aiogram/bot/telegram:latest
    - name: Publish to Github Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: docker.pkg.github.com/aiogram/bot/IMAGE_NAME:VERSION
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
