name: Docker Image CI

on:
  push:
    branches: 
      - master

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Publish to Github Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: aiogram/bot:latest
        tag: docker.illemius.xyz/aiogram/bot/app:latest
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: docker.illemius.xyz
